/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "srbtkgyegdzoqrsiitsa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyYnRrZ3llZ2R6b3Fyc2lpdHNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxODM4MjksImV4cCI6MjA4OTc1OTgyOX0.2GtvZ_AX-yECnQr8wwhhiYuVh5Zw0vJIR-hLdNh-VSU"